import type { Metadata } from 'next';
import '@/app/globals.css';
import SideNav from '@/app/ui/sidenav';
import { getDictionary } from '../languages/languages';
import { Locale } from '../lib/definitions';

export const metadata: Metadata = {
  title: 'Adesso App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);
  return (
    <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      <div className="w-full flex-none md:w-64">
        <SideNav dictionary={dictionary} />
      </div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
    </div>
  );
}
